# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4ec5d184fd253289ad6683675f941711f92b04da0e8c1846393b2b40f1a77d6bb9c0745d80bf972ebf4fa9436bbfc2d861938ca66423a476eb4ec3a0c4d314f9

test:
  secret_key_base: 83b23886abb8990469f68d55dee81ad672062619e67127f13fa47423770db0b09a7fe1aebf399193b73e98548375153c88305118a855e82a15f61076fe0a6c9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
